add preg_match expression
php-etl/string-expression-language pull request #16
Opened 2024-11-07 16:27 UTC by JoMessina

2024-11-08 13:26 UTC, sebprt reviewed
Lances php-cs-fixer pour passer le job Quality

2024-11-08 16:25 UTC, gplanchat requested changes

2024-11-08 16:25 UTC, gplanchat commented on src/StringExpressionLanguageProvider.php
> +            ExpressionFunction::fromPhp('preg_match', 'matchExpression'),
`preg_match` ne peut pas être utilisée directement, son 3e argument est passé par référence. Tu dois écrire une fonction wrapper qui permette de retourner les `$matches`.

2024-11-12 10:04 UTC, JoMessina commented on src/StringExpressionLanguageProvider.php
> +            ExpressionFunction::fromPhp('preg_match', 'matchExpression'),
Le besoin est uniquement de tester l'expression ici, j'ai réécris l'expression pour qu'on retourne un booléen en fonction du résultat de preg_match.

2024-11-12 10:09 UTC, sebprt commented on src/StringExpressionLanguageProvider.php
> +            new TestPattern('testPattern'),
On pourrait pas nommer la fonction `isMatchingPattern` ? 
Je trouve ça plus explicite que le `testPattern`

2024-11-12 13:49 UTC, closed without merging